#!/bin/bash

# lpack: temporary wrapper around the lpack scripts
#
# Note - to use this you must
#   mkdir /usr/share/lpack
#   cp *.sh usr/share/lpack
# and then probably
#   cp lpack /usr/bin
# This is clearly a very short-term hack until we switch to a single lpack go binary
#
#
# Copyright (C) 2017 Cisco Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
    echo "Usage:"
    echo "    lpack unpack - unpack an OCI layout into btrfs subvolumes"
    echo "    lpack checkout tag - checkout @tag to make changes"
    echo "    lpack checkin newtag - checkin changes, optionally with tag @newtag"
    echo "    lpack setup - setup btrfs filesystem to unpack into"
    echo "    lpack unsetup - unsetup btrfs.  Make sure to checkin changes before doing this."
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi

case "$1" in
    "checkin"|"ci") /usr/share/lpack/lpack_checkin.sh ${@:2};;
    "checkout"|"co") /usr/share/lpack/lpack_checkout.sh ${@:2};;
    "unpack") /usr/share/lpack/lpack_unpack.sh ${@:2};;
    "setup") /usr/share/lpack/setup_btrfs.sh;;
    "unsetup") /usr/share/lpack/unsetup_btrfs.sh;;
esac
